version: 2

before:
  hooks:
    - go mod verify
    - go mod vendor

builds:
  - id: antidot-home
    binary: antidot-home
    ldflags:
      - -s -w -X 'main.version={{ .Version }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: release
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    ids:
      - antidot-home

  - id: binaries
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - binary
    ids:
      - antidot-home

  - id: aur
    name_template: "aur_{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    ids:
      - antidot-home
    files:
      - none*

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  ids:
    - release
    - binaries
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^tests"
      - "^chore"

brews:
  - name: antidot-home
    repository:
      owner: bad3r
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/bad3r/antidot-home"
    description: "Cleans up your $HOME from those pesky dotfiles"
    license: "MIT"
    skip_upload: false
    ids:
      - release
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "antidot-home"
