name: Lint GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    paths:
      - ".github/workflows/**"

# Security: Set minimal permissions
permissions:
  contents: read

jobs:
  actionlint:
    name: Lint Actions
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Run actionlint
        uses: reviewdog/action-actionlint@50b75b9513baa71e6a1899a1ebaa9ac9851cf16c # v1.66.0
        with:
          reporter: github-pr-review
          fail_on_error: true
          level: error